### ISSUE TITLE
Something explodes and lags everything

### ISSUE THREAD

**Issue by Sparky976** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#168]
So me and my mates have a server with some mods i can list if you need. We had issues with the other hbm port not made by you,  so we moved to your more updated version.

We created the new world that was also a custom earth map

we then instantly heard explotions but cant find what it is. the server lags everyone out ever 5 seconds.

we are also on the lastest version of your mod on forge (1.6.4-G)

**Comment by gatoborrachon** [comment]
Disable the generation of gas bubbles inside the config

**Comment by Sparky976** [comment]
Did that and the explosions def stopped after a map restart. but there is still quite a bit of lag. Not sure exactly why. is there any other config things i could turn off to reduce this?

**Comment by gatoborrachon** [comment]
well, that was all i disabled and everything was fine again, did you disabled both the normal and the explosive gas bubbles? 

idk how the Gas Bubbles are supposed to work, if they disappear after a while or whatever, but maybe (and from my ignorance of how they work) there are some Gas Bubbles that remained in the world, and since they tick no matter if they are on a loaded or unloaded chunk (due to a bug that drillgon said in the discord server) well, i just can think that they are causing this lag, in my case, when i found this lag, i was (i still) using AromaBackup, so i only tested this with a world before the jump to 1.6.4a

but yeah, lets wait what Drillgon says

**Comment by Sparky976** [comment]
the game just needs more ram thats all. Thanks for the help

**Comment by gatoborrachon** [comment]
When you hear hoofs, think horse, not zebra

yeah, you are right, low ram is the most common cause of lag due to Garbage Collector freezing the game
