### ISSUE TITLE
even more issues

### ISSUE THREAD

**Issue by TheForge129** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#27]
-infinite fluid barrels dont work
-poisonous mud centrifuging has wierd effects, just try it, you'll see
-i can't get the plasma heater to output plasma (also i'm pretty sure it uses 10-100 times as much fuel as it's supposed to)
-xenon cycle thing is broken
-can't get the fusion reactor to accept plasma

**Comment by Drillgon200** [comment]
1. Which machines specifically don't they work on? They don't work on some because they are a pain to integrate and won't work perfectly.
2. I'll look at that later.
3. Are you sure you set it up correctly? It worked when I tested it.
4. I don't know what a xenon cycle thing is.
5. Sounds like the same thing as #3.

**Comment by TheForge129** [comment]
1: makes sense since you dropped the fluid identifier system
3. i don't even know what the setup is if i'm gonna be honest, and trust me, i've looked
4: xenon cycle thing means Linde Xenon Cycle, where you imput nothing and get 50mb of xenon... yeah, you don't get any xenon

**Comment by Drillgon200** [comment]
1. I'm not going to fix every instance of that.
2. You're almost certainly setting it up wrong.
3. Fixed.
