### ISSUE TITLE
Bombs and missiles not working

### ISSUE THREAD

**Issue by VoidZircon** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#44]
When exploding nuclear bombs the terrain is not being damaged but there is radiation.
When detonating missiles they usually explode a few seconds after launch and don't make it to their target.

**Comment by UFFR** [comment]
For that first one, that may just be do to the intensive calculations 
the algorithm makes before actually destroying blocks. It can be very 
taxing even with good computers. If the chunk is unloaded, that can also 
cause problems. Test a small nuclear bomb in creative mode, such as the 
custom nuke, and see if it actually doesn't work or if it's just because 
the device you chose was too large to be calculated in a reasonable 
amount of time. Confirm which one it was.

The second one sounds like the missile /thinks /it hit something mid-air 
and detonated prematurely. I can't determine why that would happen, 
could be a mod conflict or a genuine bug, I'd wait for Drill on that one.

On 1/21/21 8:37 PM, VoidZircon wrote:
>
> When exploding nuclear bombs the terrain is not being damaged but 
> there is radiation.
> When detonating missiles they usually explode a few seconds after 
> launch and don't make it to their target.
>
-- 
UFFR
