### ISSUE TITLE
Cascading worldgen lag

### ISSUE THREAD

**Issue by abel1502** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#48]
During generation of new chunks, the mod triggers a lot of this:
```
[Info: 2021-02-13 21:09:56.0842625: GameCallbacks.cpp(162)] Game/FML (Server thread) Warn HBM's Nuclear Tech Mod loaded a new chunk [-32, -6] in dimension 0 (overworld) while populating chunk [-32, -5], causing cascading worldgen lag.
[Info: 2021-02-13 21:09:56.0843289: GameCallbacks.cpp(162)] Game/FML (Server thread) Warn Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
```
I'm not a minecraft modder myself, but after looking into the problem a bit, I've found a possible solution: according to [this](https://forum.mcmodding.ru/threads/generacija-1-12-2-konsultacija.24415/) forum thread (which is in russian, sorry) and [this](https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/) reddit post (which, now that I look at it, actually gives a much clearer explanation), the problem is caused by structure generation overflowing into the neighbouring chunks from the negative x and z sides, and the common solution is to offset the possible generation area by 8 on both of those axis. It is stated to be done this way in vanilla minecraft worldgen, as well. In case of this mod, I believe it should concern the following lines:

https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/blob/d7036aa6aebfb5b0a72b17e19fe8e832980c7da8/src/main/java/com/hbm/lib/HbmWorldGen.java#L60-L76

+8 needs to be added to every `chunkX * 16` and `chunkX * 16` here. As it would be a bit troubling for me to compile the changed code to test the fix, I don't feel confident enough to implement it myself and make a pull request, and would much rather the original developer do it.

Also, I'm sorry for any English mistakes and for the general inconvenience of demanding a fix instead of providing one, and I really do hope someone more experienced implements and tests this so that I can finally play with this glorious mod. Thanks in advance.

**Comment by Drillgon200** [comment]
From explanation in discord message:
I'm well aware of this issue, and it would take a large amount of effort to fix for not much benefit. NTM uses WorldGenMinable for its ores, which already adds the +8 offset. In addition, it also adds an offset of 8 after all the regular ores are generated. I believe the actual issue is tha many of NTM's structures and some ores are simply larger than 8 blocks. Still, this doesn't typically cause all that much cascading chunk generation since the structures and ores larger than 8 blocks are generally more than a couple chunks between each other, so I decided it wasn't worth it to go about implementing a fix. If the log message bugs you, there is an option to turn it off in forge's config.
