### ISSUE TITLE
Fleija explosion disabled

### ISSUE THREAD

**Issue by abel1502** [Drillgon200/Hbm-s-Nuclear-Tech-GIT#69]
In the current update, fleija explosion is commented out :|
I guess it shouldn't be.

https://github.com/Drillgon200/Hbm-s-Nuclear-Tech-GIT/blob/d7036aa6aebfb5b0a72b17e19fe8e832980c7da8/src/main/java/com/hbm/blocks/bomb/NukeFleija.java#L124

**Comment by Drillgon200** [comment]
![long_ducc](https://user-images.githubusercontent.com/50186362/114076279-575b9e00-985b-11eb-805b-73dafb266e9f.png)

**Comment by abel1502** [comment]
Is it fixed? I don't see any new commits in any of the branches :|||

**Comment by Drillgon200** [comment]
I don't make commits for small changes like this (in fact, I don't commit until I actually make a release due to not feeling it necessary). If you haven't noticed, I haven't made commits to anything on this project in months. That doesn't mean I haven't been working on it.

**Comment by abel1502** [comment]
Oh. Yeah, it makes sense now. Although that's one weird way to use use git, to be honest)

**Comment by Drillgon200** [comment]
My original reason for using github at all was so that I could easily transfer my work between three computers throughout the day. I only have one computer now, so it isn't necessary. Now I update it simply to make all my code open and free to use. I have no clue how to use git or what the benefits are beyond that.
